---
layout: cv
title: Cayden Lords's CV
---
# Cayden Lords
Student, Programmer, Nerd

## Currently

A Senior in Computer Science

### Specialized in

Software Design, Variety in Programming Languages, Logic 

## Education

`May 2020`
__Madison High School__
- 3.88 GPA
- Focus on Electronics and computers

`2021 - now`
__Brigham Young University, Idaho__

- Current GPA: 3.9

## Occupation

`January 2025 - Current`
__Intro to Robotics Teaching Assistant__, BYU-I

- Introducing students to rudimentary robotics including Arduino 
- Guiding employment of basic robotic principles in small projects
- Assisting students with lab work including grading work


`September 2022 - April 2023`
__Programming Teaching Assistant__, BYU-I 

- Provided one-on-one student assistance in understanding of material in person, over Zoom, and through email
- Oversaw group work and answered both practical and theoretical questions
- Graded weekly assignments and exams


<!-- ### Footer

Last updated: July 2025 -->